#! /usr/bin/perl

##############################################################################
# pop                                   Version 1.0                          #
# Copyright 2008 Brendan Johan Lee      brendan.johan.lee@gmail.com          #
# Created 28.07.2008                    Last Modified 30.07.2008             #
# Latest version available from         www.gsmblog.net and www.vanntett.net #
##############################################################################
# Copyright (C) 2008 Brendan Johan Lee <brendan.johan.lee@gmail.com>         #
#                                                                            #
# This program is free software; you can redistribute it and/or modify       #
# it under the terms of the GNU General Public License as published by       #
# the Free Software Foundation; either version 2 of the License, or          #
# (at your option) any later version.                                        #
#                                                                            #
# This program is distributed in the hope that it will be useful,            #
# but WITHOUT ANY WARRANTY; without even the implied warranty of             #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
# GNU General Public License for more details.                               #
#                                                                            #
# You should have received a copy of the GNU General Public License          #
# along with this program; if not, write to the Free Software                #
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. #
# or see http://www.gnu.org/                                                 #
#                                                                            #
##############################################################################

##############################################################################
# pop is a helper program to be used together with FlicServ. See the         #
# FlicServ file for more information.                                        #
##############################################################################

use Socket;

my $host = shift || 'localhost';
my $port = shift || 7890;
my $proto = getprotobyname('tcp');
my $iaddr = inet_aton($host);
my $paddr = sockaddr_in($port, $iaddr);

socket(SOCKET, PF_INET, SOCK_STREAM, $proto) or die "socket: $!";
connect(SOCKET, $paddr) or die "connect: $!";

while (defined($line = <SOCKET>))
{
	print $line;
}
close SOCKET or die "close: $!"; 
